movie_1995 = {
    "status": "success",
    "data": {
        "id": 1995,
        "name": "Clueless",
        "slug": "clueless",
        "image": "https://artworks.thetvdb.com/banners/movies/1995/posters/2152857.jpg",
        "nameTranslations": [
            "ces",
            "deu",
            "spa",
            "ita",
            "hun",
            "kor",
            "zho",
            "pol",
            "por",
            "rus",
            "tur",
            "eng",
            "pt",
            "fra",
            "fra",
            "zho",
            "ara",
            "spa",
            "spa",
        ],
        "overviewTranslations": [
            "ces",
            "deu",
            "spa",
            "ita",
            "hun",
            "kor",
            "zho",
            "pol",
            "por",
            "rus",
            "tur",
            "eng",
            "pt",
            "fra",
            "fra",
            "zho",
            "ara",
            "spa",
        ],
        "aliases": [
            {"language": "fra", "name": "Les collégiennes de Beverly Hills"},
            {"language": "zho", "name": "性。衣服。人氣。這裡有問題嗎？"},
            {"language": "spa", "name": "Clueless (Fuera de onda)"},
            {"language": "spa", "name": "Ni idea"},
        ],
        "score": 541326,
        "runtime": 97,
        "status": {
            "id": 5,
            "name": "Released",
            "recordType": "movie",
            "keepUpdated": True,
        },
        "lastUpdated": "2026-02-14 03:29:12",
        "year": "1995",
    },
}
