movie_1 = {
    "status": "success",
    "data": {
        "id": 1,
        "name": "Alita: Battle Angel",
        "slug": "alita-battle-angel",
        "image": "https://artworks.thetvdb.com/banners/v4/movie/1/posters/681ab4b1789c0.jpg",
        "nameTranslations": [
            "hun",
            "jpn",
            "kor",
            "fra",
            "ces",
            "zho",
            "ita",
            "spa",
            "por",
            "rus",
            "heb",
            "tur",
            "slv",
            "deu",
            "eng",
            "pt",
            "pol",
        ],
        "overviewTranslations": [
            "hun",
            "jpn",
            "kor",
            "fra",
            "ces",
            "zho",
            "ita",
            "spa",
            "por",
            "rus",
            "heb",
            "tur",
            "slv",
            "deu",
            "eng",
            "pt",
            "pol",
            "pol",
        ],
        "aliases": [],
        "score": 410209,
        "runtime": 122,
        "status": {
            "id": 5,
            "name": "Released",
            "recordType": "movie",
            "keepUpdated": True,
        },
        "lastUpdated": "2025-09-27 08:47:32",
        "year": "2019",
    },
}
